### ISSUE TITLE
As a user I want a view that allows me to search for a specific national park and be shown a list of activities that are available in the park so that I can see what activities interest me and help plan my trip

### ISSUE THREAD

**Issue by savannahmarshall** [savannahmarshall/Trip-Planner#10]
As a user I want a view that allows me to search for a specific national park and be shown a list of activities that are available in the park so that I can see what activities interest me and help plan my trip.

Acceptance Criteria:
- It is done when the user can search a park name into the search bar.
- It is done when a list of activities for the park is displayed to the user.

**Comment by savannahmarshall** [comment]
As a user I want a view that allows me to search for a specific national park and be shown a list of activities that are available in the park so that I can see what activities interest me and help plan my trip.

Acceptance Criteria:
- It is done when the user can search a park name into the search bar.
- It is done when a list of activities for the park is displayed to the user.

**Comment by danielleboe** [comment]
National Parks API key: 92lNKhVrt2znf1zlwHNEEHOPh3xgkEzldzJfhZ63
