### ISSUE TITLE
As a user I want a navigation bar that has a link to the park search page, the saved activities, login modal and create account modal so that I can easily navigate the site

### ISSUE THREAD

**Issue by savannahmarshall** [savannahmarshall/Trip-Planner#15]
As a user I want a navigation bar that has a link to the park search page, the saved activities, login modal and create account modal so that I can easily navigate the site.

Acceptance Criteria:
- It is done when I view a navigation bar with the appropriate links.

**Comment by danielleboe** [comment]
currently blocked - pending implementation of login/logout logic to be applied.
